services:
  stats-db:
      image: postgres:16.1
      container_name: postgres
      ports:
        - "6541:5432"
      environment:
        - TZ=Europe/Moscow
        - POSTGRES_PASSWORD=stats
        - POSTGRES_USER=stats
        - POSTGRES_DB=stats
      healthcheck:
        test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
        timeout: 5s
        interval: 5s
        retries: 10

  stats-service:
    build: stats-service/stats-service-server
    image: stats-service/stats-service-server:1.0.0
    container_name: stats-service
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats
      SPRING_DATASOURCE_PASSWORD: stats
    ports:
      - "9090:9090"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9090/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:16.1
#    container_name: postgres
#    ports:
#      - "6541:5432"
#    environment:
#      - TZ=Europe/Moscow
#      - POSTGRES_PASSWORD=ewmdb
#       - POSTGRES_USER=ewmdb
#      - POSTGRES_DB=ewmdb
#    healthcheck:
#        test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
#        timeout: 5s
#        interval: 5s
#        retries: 10